function parabolaOptimFigure

thesisOptions = thesisParams;
x = -10:0.01:10;
y = @(x) (x-2).^2+2; % parabola function
fontSize = 10;
font = 'helvetica';

%%
h =figure;
plot(x, y(x),...
    "Color",thesisOptions.royalBlue,...
    'lineWidth', 2); hold on
% line
line([-5, -2], y([-5,-5]),...
    'color', 'k',...
    'handlevisibility', 'off')
% line
line([-2, -2], [y(-5), y(-2)],...
    'color', 'k',...
    'handlevisibility', 'off')
line([-2, -0], y([-2,-2]),...
    'color', 'k',...
    'handlevisibility', 'off')
% line
line([0, 0], [y(-2), y(0)],...
    'color', 'k',...
    'handlevisibility', 'off')

scatter([-5,-2, 0], [y([-5, -2, 0])], 40,...
    'filled', 'markerfacecolor', thesisOptions.gray)


% annotations
% [x, y, width, height]
annotation('textbox',[0.38, 0.22  0.1 0.1],'String',1,'FitBoxToText','on',...
               'EdgeColor', 'none',...
               'FontName', font,...
               'FontSize', fontSize);
annotation('textbox',[0.27, 0.33  0.1 0.1],'String',2,'FitBoxToText','on',...
               'EdgeColor', 'none',...
               'FontName', font,...
               'FontSize', fontSize);

annotation('textbox',[0.35, 0.37  0.1 0.1],'String','3.  \Delta f(x)','FitBoxToText','on',...
               'EdgeColor', 'none',...
               'FontName', font,...
               'FontSize', fontSize);

annotation('textbox',[0.53, 0.2  0.1 0.1],'String',4,'FitBoxToText','on',...
               'EdgeColor', 'none',...
               'FontName', font,...
               'FontSize', fontSize);


axis square
boto


set(h, 'PaperUnits', 'centimeters');
set(h, 'PaperPosition', [0 0 8.6 8.6]);
exportgraphics(h, 'C:\Users\hscott\Documents\Thesis\Figures\parabolaGradient.pdf')
